theory:
    camb:
      extra_args:
        bbn_predictor: PArthENoPE_880.2_standard.dat
        lens_potential_accuracy: 1
        num_massive_neutrinos: 1
        nnu: 3.046
        theta_H0_range:
        - 20
        - 100
#    theory_lss.HEFT.HEFTCalculator: null
    theory_lss.RSD.RSDCalculator: null

likelihood:
  lss_likelihood.wl_x_rsd.HarmonicSpaceWLxRSD :
    datavector_info_filename : /global/project/projectdirs/desi/users/jderose/CobayaLSS/pt_challenge.yaml
    use_lens_samples: [2]
    zmin_proj: 0.0
    zmax_proj: 2.0
    nz_proj: 20
    
    params:
      b1_2:
        prior:
          dist: uniform
          min: 0.5
          max: 3.0
        latex: b_1
      b2_2:
        prior:
          dist: uniform
          min: -20.0
          max: 20.0
        latex: b_2
      bs_2:
        prior:
          dist:  uniform
          min: -20.0
          max: 20.0
      alpha0_2:
        prior:
          dist:  uniform
          min: -200.0
          max: 200.0
      alpha2_2:
        prior:
          dist:  uniform
          min: -200.0
          max: 200.0
      bk_2: 0.0
      b3_2: 0.0
      alpha4_2: 0.0
      alpha6_2: 0.0
      sn_2:
        prior:
          dist:  uniform
          min:   -2000.0
          max: 2000.0
      sn2_2:
        prior:
          dist:  uniform
          min:   -100000.0
          max: 100000.0
      sn4_2: 0

params:
    logA:
      prior:
        dist: uniform
        min: 2
        max: 4
      proposal: 0.001
      latex: \log(10^{10} A_\mathrm{s})
      drop: true
    As:
      value: 'lambda logA: 1e-10*np.exp(logA)'
      latex: A_\mathrm{s}
    ns: 0.9649
    H0:
      prior:
        dist: uniform
        min: 50.0
        max: 80.0
    w: -1.0
    omegam:
      prior:
        dist: uniform
        min: 0.2
        max: 0.4
      latex: \Omega_\mathrm{m}
    omch2:
      value : 'lambda omegam, ombh2, H0 : (omegam - ombh2 / (H0 / 100)**2) * (H0 / 100)**2'
      derived : False
    ombh2:
      value : 'lambda omegam, H0 : 0.1571 * omegam * (H0 / 100)**2'
      derived : False
    mnu: 0.00
    omega_de:
      latex: \Omega_\Lambda
    YHe:
      latex: Y_\mathrm{P}
    Y_p:
      latex: Y_P^\mathrm{BBN}
    DHBBN:
      derived: 'lambda DH: 10**5*DH'
      latex: 10^5 \mathrm{D}/\mathrm{H}
    tau: 0.066
    zre:
      latex: z_\mathrm{re}
    s8h5:
      derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
      latex: \sigma_8/h^{0.5}
    s8omegamp5:
      derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
      latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
    s8omegamp25:
      derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
      latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
      
sampler:
  mcmc:
    drag: true
    oversample_power: 0.4
    proposal_scale: 1.9
    covmat: auto
    Rminus1_stop: 0.01
    Rminus1_cl_stop: 0.2
  
timing: False
output: /global/cscratch1/sd/jderose/cobaya_heft/chains/unit_redmagic_3x2pt_s8_om_bias
stop_on_error: True
emulate:
  likelihood :
    lss_likelihood.wl_x_rsd.HarmonicSpaceWLxRSD : [pkell_spectra]

  output_filename : /global/cscratch1/sd/jderose/cobaya_heft/chains/ptchallenge_cmass2_20xfast_2e6pts_training_data_v2.h5
  nstart: 0
  nend: 4000000
  param_names_fast: ['b1_2', 'b2_2', 'bs_2', 'alpha0_2', 'alpha2_2', 'sn_2', 'sn2_2']
  nfast_per_slow: 20

