training_filename: /global/cscratch1/sd/jderose/cobaya_heft/chains/unit_redmagic_wl_x_rsd_allpars_broad_bias_20xfast_1e6pts_training_data.h5
output_path: /global/cscratch1/sd/jderose/cobaya_heft/chains/unit_redmagic_wl_x_rsd_allpars_broad_bias_20xfast_1e6pts_dsx1_training_data_p0_emu_nl4_nnpl128
target: p0
param_dataset: params_pkell
use_asinh: True
scale_by_std: True
n_epochs: 30
n_pcs: 110
n_hidden: [128, 128, 128, 128]
downsample: 1