theory:
    camb:
      extra_args:
        bbn_predictor: PArthENoPE_880.2_standard.dat
        lens_potential_accuracy: 1
        num_massive_neutrinos: 1
        nnu: 3.046
        theta_H0_range:
        - 20
        - 100
    theory_lss.HEFT.HEFTCalculator: null
    theory_lss.RSD.RSDCalculator: null

likelihood:
  lss_likelihood.wl_x_rsd.HarmonicSpaceWLxRSD :
    datavector_info_filename : /global/project/projectdirs/desi/users/jderose/CobayaLSS/unit_redmagic_wl_rsd_data.yaml
    zmin_proj: 0.0
    zmax_proj: 2.0
    nz_proj: 20
    
    params:
      b1_0:
        prior:
          dist: uniform
          min: 0.0
          max: 3.0
        latex: b_1
      b2_0:
        prior:
          dist: uniform
          min: -5.0
          max: 5.0
        latex: b_2
      bs_0:
        prior:
          dist: uniform
          min: -5.0
          max: 5.0
        latex: b_s
      b3_0:
        prior:
          dist: uniform
          min: -5.0
          max: 5.0
        latex: b_3
      bk_0:
        prior :
          dist: uniform
          min: -100.0
          max: 100.0
        latex: b_k
      alpha0_0:
        prior:
          dist: uniform
          min: -100
          max: 100
        latex: alpha_0
      alpha2_0:
        prior:
          dist: uniform
          min: -100
          max: 100
        latex: alpha_2
      alpha4_0:
        prior:
          dist: uniform
          min: -100
          max: 100
        latex: alpha_4
      alpha6_0:
        prior:
          dist: uniform
          min: -100
          max: 100
        latex: alpha_6
      sn_0:
        prior:
          dist: uniform
          min: 0
          max: 10000
        latex: SN_0
      sn2_0:
        prior:
          dist: uniform
          min: 0
          max: 10000
        latex: SN2_0
      sn4_0:
        prior:
          dist: uniform
          min: 0
          max: 10000
        latex: SN4_0

params:
    logA:
      prior:
        dist: uniform
        min: 3.0
        max: 3.18
      proposal: 0.001
      latex: \log(10^{10} A_\mathrm{s})
      drop: true
    As:
      value: 'lambda logA: 1e-10*np.exp(logA)'
      latex: A_\mathrm{s}
    ns:
      prior:
        dist: uniform
        min: 0.927
        max: 0.997
    H0:
      prior:
        dist: uniform
        min: 61.7
        max: 74.7
    w:
      prior:
        dist: uniform
        min: -1.399
        max: -0.565
    ombh2:
      prior:
        dist: uniform
        min: 0.0207
        max: 0.0237
    omch2:
      prior:
        dist: uniform
        min: 0.101
        max: 0.131
    omegam:
      latex: \Omega_\mathrm{m}
    omegamh2:
      derived: 'lambda omegam, H0: omegam*(H0/100)**2'
      latex: \Omega_\mathrm{m} h^2
    mnu: 0.00
    omega_de:
      latex: \Omega_\Lambda
    YHe:
      latex: Y_\mathrm{P}
    Y_p:
      latex: Y_P^\mathrm{BBN}
    DHBBN:
      derived: 'lambda DH: 10**5*DH'
      latex: 10^5 \mathrm{D}/\mathrm{H}
    tau: 0.066
    zre:
      latex: z_\mathrm{re}
    sigma8:
      latex: \sigma_8
    s8h5:
      derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
      latex: \sigma_8/h^{0.5}
    s8omegamp5:
      derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
      latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
    s8omegamp25:
      derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
      latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
    A:
      derived: 'lambda As: 1e9*As'
      latex: 10^9 A_\mathrm{s}
    clamp:
      derived: 'lambda As, tau: 1e9*As*np.exp(-2*tau)'
      latex: 10^9 A_\mathrm{s} e^{-2\tau}
    age:
      latex: '{\rm{Age}}/\mathrm{Gyr}'
    rdrag:
      latex: r_\mathrm{drag}
      
sampler:
  mcmc:
    drag: true
    oversample_power: 0.4
    proposal_scale: 1.9
    covmat: auto
    Rminus1_stop: 0.01
    Rminus1_cl_stop: 0.2
  
timing: False
output: /global/cscratch1/sd/jderose/cobaya_heft/chains/unit_redmagic_3x2pt_s8_om_bias
stop_on_error: True
emulate:
  likelihood :
    lss_likelihood.wl_x_rsd.HarmonicSpaceWLxRSD : [pkell_spectra]

  output_filename : /global/cscratch1/sd/jderose/cobaya_heft/chains/unit_redmagic_wl_x_rsd_allpars_broad_bias_100xfast_1e6pts_training_data_debugged.h5
  nstart: 0
  nend: 1000000
  param_names_fast: ['b1_0', 'b2_0', 'bs_0', 'b3_0', 'bk_0', 'alpha0_0', 'alpha2_0', 'alpha4_0', 'alpha6_0', 'sn_0', 'sn2_0', 'sn4_0']
  nfast_per_slow: 100

