theory:
    camb:
      extra_args:
        bbn_predictor: PArthENoPE_880.2_standard.dat
        lens_potential_accuracy: 1
        num_massive_neutrinos: 1
        nnu: 3.046
        theta_H0_range:
        - 20
        - 100
    theory_lss.HEFT.HEFTCalculator: null

likelihood:
  lss_likelihood.pk_likelihood.SimPkLikelihood :
    params:
      b1:
        prior:
          dist: uniform
          min: -0.5
          max:  2.0
        latex: b_1
      b2:
        prior:
          dist: uniform
          min: -2.0
          max: 2.0
        latex: b_2
      bs:
        prior:
          dist: uniform
          min: -2.0
          max: 2.0
        latex: b_s
      sn:
        prior:
          dist: uniform
          min: 50
          max: 2000
        latex: SN_0
      bk:
        prior :
          dist: uniform
          min: -2.0
          max: 2.0
        latex: b_k
    

params:
    logA:
      prior:
        dist: uniform
        min: 3.0
        max: 3.18
      proposal: 0.001
      latex: \log(10^{10} A_\mathrm{s})
      drop: true
    As:
      value: 'lambda logA: 1e-10*np.exp(logA)'
      latex: A_\mathrm{s}
    ns:
      prior:
        dist: uniform
        min: 0.927
        max: 0.997
    H0:
      prior:
        dist: uniform
        min: 61.7
        max: 74.7
    w:
      prior:
        dist: uniform
        min: -1.399
        max: -0.565
    ombh2:
      prior:
        dist: uniform
        min: 0.0207
        max: 0.0237
    omch2:
      prior:
        dist: uniform
        min: 0.101
        max: 0.131
    omegam:
      latex: \Omega_\mathrm{m}
    omegamh2:
      derived: 'lambda omegam, H0: omegam*(H0/100)**2'
      latex: \Omega_\mathrm{m} h^2
    mnu: 0.00
    omega_de:
      latex: \Omega_\Lambda
    YHe:
      latex: Y_\mathrm{P}
    Y_p:
      latex: Y_P^\mathrm{BBN}
    DHBBN:
      derived: 'lambda DH: 10**5*DH'
      latex: 10^5 \mathrm{D}/\mathrm{H}
    tau: 0.066
    zre:
      latex: z_\mathrm{re}
    sigma8:
      latex: \sigma_8
    s8h5:
      derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
      latex: \sigma_8/h^{0.5}
    s8omegamp5:
      derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
      latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
    s8omegamp25:
      derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
      latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
    A:
      derived: 'lambda As: 1e9*As'
      latex: 10^9 A_\mathrm{s}
    clamp:
      derived: 'lambda As, tau: 1e9*As*np.exp(-2*tau)'
      latex: 10^9 A_\mathrm{s} e^{-2\tau}
    age:
      latex: '{\rm{Age}}/\mathrm{Gyr}'
    rdrag:
      latex: r_\mathrm{drag}
      
sampler:
  mcmc:
    drag: true
    oversample_power: 0.4
    proposal_scale: 1.9
    covmat: auto
    Rminus1_stop: 0.01
    Rminus1_cl_stop: 0.2
  
timing: False
output: /global/cscratch1/sd/jderose/cobaya_heft/chains/unit_redmagic_3x2pt_s8_om_bias
stop_on_error: True
emulate:
#  provider :
#    [heft_spectrum_grid]
  likelihood :
    lss_likelihood.pk_likelihood.SimPkLikelihood: model_pred
  output_filename : /global/cscratch1/sd/jderose/cobaya_heft/chains/unit_redmagic_3x2pt_allpars_training_data.h5
  nstart: 0
  nend: 100000
